### ISSUE TITLE
Error on command `spacebro-client-cli help`

### ISSUE THREAD

**Issue by tournevis** [soixantecircuits/spacebro-client-cli#1]
Hi,

I got an error after installation on using the following command : `spacebro-client-cli help`

Here is the error : 
```
spacebro-client-cli git:(master) ✗ spacebro-client-cli help
module.js:471
    throw err;
    ^

Error: Cannot find module './config'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
```

**Comment by hugohil** [comment]
There are two issues here:

1. The `help` command is to be sent within the spacebro-cli REPL.
2. You need to `cp config.example.json config.json` for the command to get the correct config file.

Both thing are poorly explained in the README.md, I'll publish some fixes very soon.
